### PR TITLE
Bump firestore sdk dependency to version 25.0.0

### LINKED ISSUE #344: Xamarin.Firebase.Firestore 125.0.0 - System.TypeLoadException: expected class 'Firebase.Timestamp' in assembly 'Xamarin.Firebase.Firestore'
When updating `Xamarin.Firebase.Firestore` to 125.0.0, I get the following exception when retrieving a document from firestore:
```
System.TypeLoadException: Could not resolve type with token 0100007a from typeref (expected class 'Firebase.Timestamp' in assembly 'Xamarin.Firebase.Firestore, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null')
    at Plugin.Firebase.Firestore.Platforms.Android.Extensions.JavaObjectExtensions.Cast[FirestoreDocument](IDictionary`2 this, String documentId)
```

Maybe it's time to update the plugin's dependencies, and then fix this issue.
What do you think?

### PR DESCRIPTION
**Pull request by tranb3r**
Fixes #344

### CODE REVIEW

**Comment by AdamEssenmacher** [comment]
This doesn't build, at least in part because Xamarin.Firebase.Firestore isn't compatible with .net6. It's also not compatible with .net7, so a prerequisite for upgrading to Firestore 25 would be updating this plugin to .net8.

**Comment by AdamEssenmacher** [comment]
#357

**Comment by AdamEssenmacher** [comment]
@tranb3r if you wanted to expedite this getting published:

1. Checkout the .net8 branch locally
2. Copy or merge your version bump in
3. Make sure the Firestore project builds for Android
4. Spot-test a Firestore implementation that uses timestamps

**Comment by TobiasBuchholz** [comment]
Done by https://github.com/TobiasBuchholz/Plugin.Firebase/commit/b680065d52dcae82423d2c3ac0c3cbafe49bff3c

**Pull request closed without merging**
