### PR TITLE
Added a serverTimestamp attribute

### PR DESCRIPTION
**Pull request by Mataboge**
This new servertimestamp attribute auto-uploads the "real-time" servertime when the property value is written to the database and when reading from the database it returns the saved property value as normal. This addresses #12 

example use:

```
        [FirestoreServerTimestamp("LatestTime")]
        public DateTimeOffset LatestTime { get; set; }
```

### CODE REVIEW

**Comment by Kapusch** [comment]
Neat ! Thank you @Mataboge .
Could you please add a small usage example in the FirestoreFixture.cs file ?

**Comment by Mataboge** [comment]
Alright, will do

**Comment by Mataboge** [comment]
@Kapusch Done

**Comment by TobiasBuchholz** [comment]
Thanks a lot for your contribution @Mataboge!

Unfortunately it doesn't seem to work. If I run your code provided in the FirestoreFixture class, I'm receiving for both platforms the following exceptions:

**Comment by TobiasBuchholz** [comment]
Thanks a lot for your contribution @Mataboge!

Unfortunately it doesn't seem to work. If I run your code provided in the FirestoreFixture class, I'm receiving for both platforms an exception with the message `FieldValue.serverTimestamp() is not currently supported inside arrays`:

```c#
[FAIL] Plugin.Firebase.IntegrationTests.Firestore.FirestoreFixture.records_upload_servertime_to_a_property : Java.Lang.IllegalArgumentException : Invalid data. FieldValue.serverTimestamp() is not currently supported inside arrays
08-11 22:36:16.880 V/mono-stdout(12748): 	[FAIL] Plugin.Firebase.IntegrationTests.Firestore.FirestoreFixture.records_upload_servertime_to_a_property : Java.Lang.IllegalArgumentException : Invalid data. FieldValue.serverTimestamp() is not currently supported inside arrays
08-11 22:36:16.884 V/mono-stdout(12748): 		  at Java.Interop.JniEnvironment+InstanceMethods.CallObjectMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00068] in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniEnvironment.g.cs:11524 
08-11 22:36:16.885 V/mono-stdout(12748): 		  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualObjectMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x00024] in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniInstanceMethods_Invoke.cs:389 
		  at Java.Interop.JniEnvironment+InstanceMethods.CallObjectMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00068] in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniEnvironment.g.cs:11524 
08-11 22:36:16.886 V/mono-stdout(12748): 		  at Firebase.Firestore.DocumentReference.Set (Java.Lang.Object data) [0x00027] in /Users/runner/work/1/s/generated/com.google.firebase.firebase-firestore/obj/Release/monoandroid90/generated/src/Firebase.Firestore.DocumentReference.cs:523 
08-11 22:36:16.886 V/mono-stdout(12748): 		  at Plugin.Firebase.Android.Firestore.DocumentReferenceWrapper.SetDataAsync (System.Object data, Plugin.Firebase.Firestore.SetOptions options) [0x00028] in /Users/tobiasbuchholz/Projects/XamarinProjects/Plugin.Firebase/src/Android/Firestore/DocumentReferenceWrapper.cs:28 
08-11 22:36:16.886 V/mono-stdout(12748): 		  at Plugin.Firebase.IntegrationTests.Firestore.FirestoreFixture.records_upload_servertime_to_a_property () [0x000b1] in /Users/tobiasbuchholz/Projects/XamarinProjects/Plugin.Firebase/tests/Plugin.Firebase.IntegrationTests/Firestore/FirestoreFixture.cs:49 
08-11 22:36:16.887 V/mono-stdout(12748): 		  --- End of managed Java.Lang.IllegalArgumentException stack trace ---
08-11 22:36:16.887 V/mono-stdout(12748): 		java.lang.IllegalArgumentException: Invalid data. FieldValue.serverTimestamp() is not currently supported inside arrays
		  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualObjectMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x00024] in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniInstanceMethods_Invoke.cs:389 
		  at Firebase.Firestore.DocumentReference.Set (Java.Lang.Object data) [0x00027] in /Users/runner/work/1/s/generated/com.google.firebase.firebase-firestore/obj/Release/monoandroid90/generated/src/Firebase.Firestore.DocumentReference.cs:523 
		  at Plugin.Firebase.Android.Firestore.DocumentReferenceWrapper.SetDataAsync (System.Object data, Plugin.Firebase.Firestore.SetOptions options) [0x00028] in /Users/tobiasbuchholz/Projects/XamarinProjects/Plugin.Firebase/src/Android/Firestore/DocumentReferenceWrapper.cs:28 
		  at Plugin.Firebase.IntegrationTests.Firestore.FirestoreFixture.records_upload_servertime_to_a_property () [0x000b1] in /Users/tobiasbuchholz/Projects/XamarinProjects/Plugin.Firebase/tests/Plugin.Firebase.IntegrationTests/Firestore/FirestoreFixture.cs:49 
		  --- End of managed Java.Lang.IllegalArgumentException stack trace ---
		java.lang.IllegalArgumentException: Invalid data. FieldValue.serverTimestamp() is not currently supported inside arrays
```

```c#
2022-08-11 22:24:03.130746+0200 Plugin.Firebase.TestHarness.iOS[9830:295925] 	[FAIL] Plugin.Firebase.IntegrationTests.Firestore.FirestoreFixture.records_upload_servertime_to_a_property : Foundation.MonoTouchException : Objective-C exception thrown.  Name: FIRInvalidArgumentException Reason: FieldValue.serverTimestamp() is not currently supported inside arrays
2022-08-11 22:23:04.087298+0200 Plugin.Firebase.TestHarness.iOS[9830:295074] 		  at ObjCRuntime.Runtime.ThrowNSException (System.IntPtr ns_exception) [0x00000] in /Users/builder/azdo/_work/1/s/xamarin-macios/src/ObjCRuntime/Runtime.cs:441
2022-08-11 22:23:04.087546+0200 Plugin.Firebase.TestHarness.iOS[9830:295074] 		  at ObjCRuntime.Runtime.throw_ns_exception (System.IntPtr exc) [0x00000] in /Users/builder/azdo/_work/1/s/xamarin-macios/runtime/Delegates.generated.cs:392
2022-08-11 22:23:04.087765+0200 Plugin.Firebase.TestHarness.iOS[9830:295074] 		  at (wrapper native-to-managed) ObjCRuntime.Runtime.throw_ns_exception(intptr)
2022-08-11 22:23:04.088346+0200 Plugin.Firebase.TestHarness.iOS[9830:295074] 		  at (wrapper managed-to-native) ApiDefinition.Messaging.void_objc_msgSend_IntPtr_IntPtr(intptr,intptr,intptr,intptr)
2022-08-11 22:23:04.089207+0200 Plugin.Firebase.TestHarness.iOS[9830:295074] 		  at Firebase.CloudFirestore.DocumentReference.SetData (Foundation.NSDictionary`2[TKey,TValue] nsDocumentData, Firebase.CloudFirestore.DocumentActionCompletionHandler completion) [0x0004c] in <fba2b2cf52cb40559b9582b173d7548b>:0
2022-08-11 22:23:04.089964+0200 Plugin.Firebase.TestHarness.iOS[9830:295074] 		  at Firebase.CloudFirestore.DocumentReference.SetData (System.Collections.Generic.Dictionary`2[TKey,TValue] documentData, Firebase.CloudFirestore.DocumentActionCompletionHandler completion) [0x0002f] in <fba2b2cf52cb40559b9582b173d7548b>:0
2022-08-11 22:23:04.091089+0200 Plugin.Firebase.TestHarness.iOS[9830:295074] 		  at Firebase.CloudFirestore.DocumentReference.SetDataAsync (System.Collections.Generic.Dictionary`2[TKey,TValue] documentData) [0x00011] in <fba2b2cf52cb40559b9582b173d7548b>:0
2022-08-11 22:23:04.091878+0200 Plugin.Firebase.TestHarness.iOS[9830:295074] 		  at Plugin.Firebase.iOS.Firestore.DocumentReferenceWrapper.SetDataAsync (System.Collections.Generic.Dictionary`2[TKey,TValue] data, Plugin.Firebase.Firestore.SetOptions options) [0x0000a] in /Users/tobiasbuchholz/Projects/XamarinProjects/Plugin.Firebase/src/iOS/Firestore/DocumentReferenceWrapper.cs:29
2022-08-11 22:23:04.092662+0200 Plugin.Firebase.TestHarness.iOS[9830:295074] 		  at Plugin.Firebase.iOS.Firestore.DocumentReferenceWrapper.SetDataAsync (System.Object data, Plugin.Firebase.Firestore.SetOptions options) [0x00001] in /Users/tobiasbuchholz/Projects/XamarinProjects/Plugin.Firebase/src/iOS/Firestore/DocumentReferenceWrapper.cs:23
2022-08-11 22:23:04.093042+0200 Plugin.Firebase.TestHarness.iOS[9830:295074] 		  at Plugin.Firebase.IntegrationTests.Firestore.FirestoreFixture.records_upload_servertime_to_a_property () [0x00099] in /Users/tobiasbuchholz/Projects/XamarinProjects/Plugin.Firebase/tests/Plugin.Firebase.IntegrationTests/Firestore/FirestoreFixture.cs:49
2022-08-11 22:23:04.093313+0200 Plugin.Firebase.TestHarness.iOS[9830:295074] 		  at (wrapper managed-to-native) ApiDefinition.Messaging.void_objc_msgSend_IntPtr_IntPtr(intptr,intptr,intptr,intptr)
2022-08-11 22:23:04.093578+0200 Plugin.Firebase.TestHarness.iOS[9830:295074] 		  at Firebase.CloudFirestore.DocumentReference.SetData (Foundation.NSDictionary`2[TKey,TValue] nsDocumentData, Firebase.CloudFirestore.DocumentActionCompletionHandler completion) [0x0004c] in <fba2b2cf52cb40559b9582b173d7548b>:0
2022-08-11 22:23:04.093772+0200 Plugin.Firebase.TestHarness.iOS[9830:295074] 		  at Firebase.CloudFirestore.DocumentReference.SetData (System.Collections.Generic.Dictionary`2[TKey,TValue] documentData, Firebase.CloudFirestore.DocumentActionCompletionHandler completion) [0x0002f] in <fba2b2cf52cb40559b9582b173d7548b>:0
2022-08-11 22:23:04.093995+0200 Plugin.Firebase.TestHarness.iOS[9830:295074] 		  at Firebase.CloudFirestore.DocumentReference.SetDataAsync (System.Collections.Generic.Dictionary`2[TKey,TValue] documentData) [0x00011] in <fba2b2cf52cb40559b9582b173d7548b>:0
2022-08-11 22:23:04.094384+0200 Plugin.Firebase.TestHarness.iOS[9830:295074] 		  at Plugin.Firebase.iOS.Firestore.DocumentReferenceWrapper.SetDataAsync (System.Collections.Generic.Dictionary`2[TKey,TValue] data, Plugin.Firebase.Firestore.SetOptions options) [0x0000a] in /Users/tobiasbuchholz/Projects/XamarinProjects/Plugin.Firebase/src/iOS/Firestore/DocumentReferenceWrapper.cs:29
2022-08-11 22:23:04.094883+0200 Plugin.Firebase.TestHarness.iOS[9830:295074] 		  at Plugin.Firebase.iOS.Firestore.DocumentReferenceWrapper.SetDataAsync (System.Object data, Plugin.Firebase.Firestore.SetOptions options) [0x00001] in /Users/tobiasbuchholz/Projects/XamarinProjects/Plugin.Firebase/src/iOS/Firestore/DocumentReferenceWrapper.cs:23
2022-08-11 22:23:04.095416+0200 Plugin.Firebase.TestHarness.iOS[9830:295074] 		  at Plugin.Firebase.IntegrationTests.Firestore.FirestoreFixture.records_upload_servertime_to_a_property () [0x00099] in /Users/tobiasbuchholz/Projects/XamarinProjects/Plugin.Firebase/tests/Plugin.Firebase.IntegrationTests/Firestore/FirestoreFixture.cs:49
```

As you can see in the stacktraces the exception get's thrown during setting the data at the `DocumentReferenceWrapper` class, see https://github.com/TobiasBuchholz/Plugin.Firebase/blob/d4d4b0ca175ceb28fcc5b5d4e42b098ea31abbf7/src/iOS/Firestore/DocumentReferenceWrapper.cs#L29

Apparently the dictionary, that gets created from the firestore object (`Pokemon`) is not allowed to contain a FieldValue.ServerTimestamp, so the `document.SetDataAsync(dict)` method throws this exception. Unfortunately there are no overloads that are not using a dictionary at the `document.SetDataAsync()` method, so I'm afraid our hands are tied.

After taking a look at stackoverflow I've found this [issue](https://stackoverflow.com/questions/67220365/firebase-firestore-timestamp-not-allowed-inside-array) which kinda confirms the error message, so basically I'm wondering how you've got it to work with your code.

**As a workaround** you can use the `document.UpdateAsync()` that uses tuples as parameters, so something like this:
```c#
await document.UpdateDataAsync(("updated_at", FieldValue.ServerTimestamp()));
```
With this code you don't need a `FirestoreServertimeStamp` attribute anymore, but can just use the regular `FirestoreProperty` attribute with `updated_at` as value and it will get set automatically as expected.

**Comment by Mataboge** [comment]
Hi @TobiasBuchholz , I can confirm this error that you are receiving and it is caused by this property in your pokemon.cs
```
        [FirestoreProperty("evolutions")]
        public IList<Pokemon> Evolutions { get; private set; }
```
A C# list gets converted to an array in the Firestore database, but firestore does not allow uploading of an array with FieldValue children, hence the error. In my code it works because my database structure not have an array with a model(that has an servertimestamp property) as its children, I implement such a need as a subcollection instead. 

If you don't upload evolutions property, it should work (or make evolutions a subcollection)

The workaround you proposed below is not ideal in my case because i would have to **write** all other properties to the database, then update the "updated_at" property immediately after. That is **2 write operations** for every write that i have to do, for a large database (or a chat-app) you can image the write cost that i incur every month. It essentially doubles my write operations.

`await document.UpdateDataAsync(("updated_at", FieldValue.ServerTimestamp()));`

**Comment by TobiasBuchholz** [comment]
Aaah I see, you are right. The evolutions array was supposed to show that arrays with objects are working as well in the firestore. But since it's causing problems now, I've replaced it with a list of `SimpleItem`s, so the tests in the `FirestoreFixture` class are working again and your PR can be merged into the development branch :)

**Pull request merged**
